// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh_nSQM1evjSOUsRsNrrxz58R_VX_4Ni4',
    appId: '1:779488882287:web:730cbe610a36cdc6d5679a',
    messagingSenderId: '779488882287',
    projectId: 'shopping-app-bcc8f',
    authDomain: 'shopping-app-bcc8f.firebaseapp.com',
    storageBucket: 'shopping-app-bcc8f.firebasestorage.app',
    measurementId: 'G-LN0JMJVCCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhTLQJXIi4d1HCXq2s959x0F2gynFAeaI',
    appId: '1:779488882287:android:2193d2845e8e1ecdd5679a',
    messagingSenderId: '779488882287',
    projectId: 'shopping-app-bcc8f',
    storageBucket: 'shopping-app-bcc8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGw4RZYxda2LNo3-Tv2MAaffyJhn0_6Sw',
    appId: '1:779488882287:ios:cee133e7c77b74e3d5679a',
    messagingSenderId: '779488882287',
    projectId: 'shopping-app-bcc8f',
    storageBucket: 'shopping-app-bcc8f.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGw4RZYxda2LNo3-Tv2MAaffyJhn0_6Sw',
    appId: '1:779488882287:ios:cee133e7c77b74e3d5679a',
    messagingSenderId: '779488882287',
    projectId: 'shopping-app-bcc8f',
    storageBucket: 'shopping-app-bcc8f.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh_nSQM1evjSOUsRsNrrxz58R_VX_4Ni4',
    appId: '1:779488882287:web:68af040d58211646d5679a',
    messagingSenderId: '779488882287',
    projectId: 'shopping-app-bcc8f',
    authDomain: 'shopping-app-bcc8f.firebaseapp.com',
    storageBucket: 'shopping-app-bcc8f.firebasestorage.app',
    measurementId: 'G-ZLDC5ZVP5G',
  );
}
